### PR TITLE
Added Squaremap Support

### PR DESCRIPTION
**Pull request by CoolDCB**
I've added support for squaremap, it is mostly working but the WorldIdentifier#create requires namespace keys/values that aren't accessibly through the World object

- [ ] Add multiple world support

### CODE REVIEW

**Comment by WiIIiam278** [comment]
Hey! Appreciate your work -- very sorry, though, but I'm declining this PR. I wish to support Pl3xMap v2 only. I consider SquareMap legacy and don't want to support an old fork. Thank you nonetheless for your interest -- if there's anything else you wish to tackle, feel free to open another PR.

**Comment by CoolDCB** [comment]
> Hey! Appreciate your work -- very sorry, though, but I'm declining this PR. I wish to support Pl3xMap v2 only. I consider SquareMap legacy and don't want to support an old fork. Thank you nonetheless for your interest -- if there's anything else you wish to tackle, feel free to open another PR.

All good! I wasn't actually aware of [pl3x map](https://modrinth.com/plugin/pl3xmap), I'd be happy to create a PR and add support for that instead. I was only starting looking into using a web map plugin but wanted something more lightweight so Pl3xMap seems to be a good choice for me nonetheless

_Just to check is that the right link?_

**Comment by WiIIiam278** [comment]
> > Hey! Appreciate your work -- very sorry, though, but I'm declining this PR. I wish to support Pl3xMap v2 only. I consider SquareMap legacy and don't want to support an old fork. Thank you nonetheless for your interest -- if there's anything else you wish to tackle, feel free to open another PR.
> 
> All good! I wasn't actually aware of [Pl3xMap](https://modrinth.com/plugin/pl3xmap), I'd be happy to create a PR and add support for that instead. I was only starting looking into using a web map plugin but wanted something more lightweight so Pl3xMap seems to be a good choice for me nonetheless
> 
> _Just to check is that the right link?_
> 
> edit: do you think adding support for this would be better implemented into the Pl3xMap-Claims plugin?

Hey!

Yeah, so to catch you up, a brief history of Pl3xMap and SquareMap
* jpnella & BillyG (original creator of Purpur/a notable performance fork) made the original Pl3xMap a few years back - super fast and lightweight compared to the offerings of the time
* Billy discontinued work on Pl3xMap due to time. Two forks came about:
  * jmp forked the plugin and the fabric client (renamed to squaremap) and is offering support on the M.O.S.S. discord at https://discord.gg/PHpuzZS
  * NeumimTo forked the plugin and is offering support on the G.E.A.R.S discord at https://discord.gg/y66aV9VC6s
* Billy returns! Pl3xMap went through two iterations - v2 (short-lived) and now the excellent v3, which is cross-platform! This is what I'm targeting with HuskHomes (https://github.com/WiIIiam278/HuskHomes/blob/master/common/src/main/java/net/william278/huskhomes/hook/Pl3xMapHook.java) -- and would love to target for HuskTowns, too (see #282)

I'd love to support Pl3xMap v3, as it's the latest in the chain! Super sorry for flushing this work down the drain though D: Really appreciate your interest nevertheless!

If you're interested, I'd love a PR for Pl3x support -- you can use HuskHomes' impl as reference (add it to the common module, feel free to use the Homes code as skeleton and look at Towns' BlueMap/DynMap hooks)

Many thanks!

**Comment by CoolDCB** [comment]
> > > Hey! Appreciate your work -- very sorry, though, but I'm declining this PR. I wish to support Pl3xMap v2 only. I consider SquareMap legacy and don't want to support an old fork. Thank you nonetheless for your interest -- if there's anything else you wish to tackle, feel free to open another PR.
> > 
> > 
> > All good! I wasn't actually aware of [Pl3xMap](https://modrinth.com/plugin/pl3xmap), I'd be happy to create a PR and add support for that instead. I was only starting looking into using a web map plugin but wanted something more lightweight so Pl3xMap seems to be a good choice for me nonetheless
> > _Just to check is that the right link?_
> > edit: do you think adding support for this would be better implemented into the Pl3xMap-Claims plugin?
> 
> Hey!
> 
> Yeah, so to catch you up, a brief history of Pl3xMap and SquareMap
> 
> * jpnella & BillyG (original creator of Purpur/a notable performance fork) made the original Pl3xMap a few years back - super fast and lightweight compared to the offerings of the time
> * Billy discontinued work on Pl3xMap due to time. Two forks came about:
>   
>   * jmp forked the plugin and the fabric client (renamed to squaremap) and is offering support on the M.O.S.S. discord at https://discord.gg/PHpuzZS
>   * NeumimTo forked the plugin and is offering support on the G.E.A.R.S discord at https://discord.gg/y66aV9VC6s
> * Billy returns! Pl3xMap went through two iterations - v2 (short-lived) and now the excellent v3, which is cross-platform! This is what I'm targeting with HuskHomes (https://github.com/WiIIiam278/HuskHomes/blob/master/common/src/main/java/net/william278/huskhomes/hook/Pl3xMapHook.java) -- and would love to target for HuskTowns, too (see [Pl3xMap support #282](https://github.com/WiIIiam278/HuskTowns/issues/282))
> 
> I'd love to support Pl3xMap v3, as it's the latest in the chain! Super sorry for flushing this work down the drain though D: Really appreciate your interest nevertheless! (yes, that is the right link!)
> 
> If you're interested, I'd love a PR for Pl3x support -- you can use HuskHomes' impl as reference (add it to the common module, feel free to use the Homes code as skeleton and look at Towns' BlueMap/DynMap hooks)
> 
> Many thanks!

Thank you for that information I was really confused about the background haha.

No worries at all, it was a nice little break from working on my projects! 

I'd be more than happy to work on Pl3x v3 support in a separate PR when I wakeup tomorrow!

**Pull request closed without merging**
