### PR TITLE
Update zh-cn.yml

### PR DESCRIPTION
**Pull request by MSCMDD**
Update zh-cn.yml Update to 1.20.2

### CODE REVIEW

**Review by WiIIiam278 — CHANGES_REQUESTED** [review]
Thanks for your work - but could you remove changes to files other than the locales (zh-cn)? 

The CI is setup to publish continuously to my maven repo and these changes would break that :-) I'll update the runServer myself to 1.20.2 soonish.

**Review by MSCMDD — COMMENTED** [review]
Completed

**Comment by MSCMDD** [comment]
Emmmmm
Because I don't know how to delete the previous modifications, I have two requests.
QAQ

**Comment by YuanYuanOwO** [comment]
> Emmmmm Because I don't know how to delete the previous modifications, I have two requests. QAQ

直接关闭该 PR 即可
just close the pull request

**Comment by WiIIiam278** [comment]
Closing in favour of #345 :)

**Pull request closed without merging**
